### ISSUE TITLE
[Question] Need Help Installing

### ISSUE THREAD

**Issue by minh-le-99** [facebookresearch/nocturne#43]
### Question

Hello, I am a student doing AI research and currently trying to set up Nocturne into my school pc:

![image](https://user-images.githubusercontent.com/110433411/182729536-58edba70-4094-4dce-919c-c1fcbc8428d1.png)
![image](https://user-images.githubusercontent.com/110433411/182729515-5fc6ae71-bde3-41d2-b949-092d03839fb3.png)

My Visual Studio Code runs into this error after trying to run the files, please let me know if you have any suggestions/advice!

**Comment by eugenevinitsky** [comment]
Which command did you run to get this error?

**Comment by minh-le-99** [comment]
I right click in the create_env.py file and "Run Current File in Interactive Window"

**Comment by minh-le-99** [comment]
Is there possibly any video tutorial that I can check out with how to use Visual Studio/CMake/SMFL to run Nocturne?

**Comment by eugenevinitsky** [comment]
We don't have that yet, no. Can you confirm that you successfully completed all the installation steps? Also, are you running this in a jupyter notebook (as it seems above?)

**Comment by minh-le-99** [comment]
![image](https://user-images.githubusercontent.com/110433411/182948735-1beba656-a576-477c-92aa-b18a05aa3c56.png)

I cannot confirm that I install everything correctly :( However, I was able to successfully build the Nocturne folder from Github in SMFL - Microsoft Visual Studio. In the picture below in the bottom left, it said the build succeeded. Does this seem correct?

**Comment by eugenevinitsky** [comment]
I'm not sure, what are you showing me in the window? Sorry, could you confirm again that you followed the build instructions or was there something blocking you from doing so?

**Comment by minh-le-99** [comment]
Yea, sorry I'll write down my process so far, please let me know if I am missing anything:
1) I installed the dependencies, Cmake and downloaded the SMFL. In Cmake I configurated/generate the files using Visual Studio Code(2017). 
2) In my command prompt, I have install the git submodules, and did "python setup.py develop" to install Nocturne. 
3) In Visual Studio Code, I go into the create_env.py folder and try to run it, and it would give me the "ipykernel" error like in the first picture I posted.

**Comment by nathanlct** [comment]
As far as I can tell that error seems unrelated to Nocturne? The error
seems to be that you’re missing a jupyter-related package and it is giving
you the command to install it. Have you tried that?

On a second note, I’m seeing python3.9 while Nocturne should be installed
in 3.8 by default. Did you create a conda environment, as mentioned in the
installation instructions? If so, did you activate the environment (`conda
activate nocturne`) before executing the Python file?

You could also try running the file in the terminal directly (`python
name_of_file.py`) to make sure that the problem is jupyter-related.

**Comment by eugenevinitsky** [comment]
Closed as stale, please re-open if needed.
